version: '3'

services:
  # Your Node.js server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  # Container for running tests with Jest
  test-runner:
    depends_on:
      - app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - APP_URL=http://app:3000
    command: ["npm", "run", "test"]
