name: Build and Test Docker Image
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Build Docker Image
        run: |
          docker build -t your-docker-image-name .

      - name: Run Docker Compose and Log to File
        run: |
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit 2>&1 | tee tests.log

      - name: Check Docker Compose Exit Code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Docker Compose failed with exit code $exit_code"
            exit 1
          fi
      - name: Stop and Remove Docker Containers
        run: |
          docker-compose -f docker-compose.test.yml down

