name: Build and Test Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t your-docker-image-name .

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit

      - name: Check Docker Compose Exit Code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Docker Compose failed with exit code $exit_code"
            exit 1
          fi

      - name: Check Endpoint
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/movies)
          echo "HTTP response code: $response_code"
          if [ "$response_code" != "200" ]; then
            echo "Endpoint check failed!"
            exit 1
          fi

      - name: Stop and Remove Docker Containers
        run: |
          docker-compose -f docker-compose.test.yml down

      - name: Stop and Remove Docker Container
        run: |
          docker stop $(docker ps -q)
          docker rm $(docker ps -aq)
